package escobar_ayleen_proyecto.javaticket;

import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.*;

public class Main extends javax.swing.JFrame {

    public Main() {
        initComponents();
        Inicio();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jP_login = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTF_username = new javax.swing.JTextField();
        jPF_password = new javax.swing.JPasswordField();
        jBtn_ingresar = new javax.swing.JButton();
        jLabel34 = new javax.swing.JLabel();
        jP_MenuPrincipal = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        Usuario = new javax.swing.JLabel();
        TipoUsuario = new javax.swing.JLabel();
        jP_Eventos = new javax.swing.JPanel();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jButton31 = new javax.swing.JButton();
        jP_TEvento = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton33 = new javax.swing.JButton();
        jP_CrearEventoD = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel8 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jSpinner2 = new javax.swing.JSpinner();
        jButton5 = new javax.swing.JButton();
        jTextField5 = new javax.swing.JTextField();
        jButton19 = new javax.swing.JButton();
        jLabel35 = new javax.swing.JLabel();
        jTextField13 = new javax.swing.JTextField();
        jP_CrearEventoM = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jLabel25 = new javax.swing.JLabel();
        jSpinner3 = new javax.swing.JSpinner();
        jLabel26 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jSpinner4 = new javax.swing.JSpinner();
        jButton6 = new javax.swing.JButton();
        jComboBox5 = new javax.swing.JComboBox<>();
        jButton20 = new javax.swing.JButton();
        jP_CrearEventoR = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jDateChooser3 = new com.toedter.calendar.JDateChooser();
        jLabel33 = new javax.swing.JLabel();
        jSpinner5 = new javax.swing.JSpinner();
        jLabel36 = new javax.swing.JLabel();
        jSpinner6 = new javax.swing.JSpinner();
        jButton7 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jP_EliminarEvento = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jButton14 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jP_Users = new javax.swing.JPanel();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jLabel43 = new javax.swing.JLabel();
        jButton32 = new javax.swing.JButton();
        jP_CrearUser = new javax.swing.JPanel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel41 = new javax.swing.JLabel();
        jTF_contra = new javax.swing.JTextField();
        jTF_nombre = new javax.swing.JTextField();
        jTF_usernamee1 = new javax.swing.JTextField();
        jLabel42 = new javax.swing.JLabel();
        jS_edad = new javax.swing.JSpinner();
        jButton8 = new javax.swing.JButton();
        jP_Reportes = new javax.swing.JPanel();
        jButton25 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        jButton27 = new javax.swing.JButton();
        jButton28 = new javax.swing.JButton();
        jButton29 = new javax.swing.JButton();
        jButton30 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("LOGIN");

        jLabel3.setText("Usuario:");

        jLabel4.setText("Contraseña:");

        jTF_username.setText("admin");

        jPF_password.setText("supersecreto");

        jBtn_ingresar.setText("Ingresar");
        jBtn_ingresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_ingresarActionPerformed(evt);
            }
        });

        jLabel34.setFont(new java.awt.Font("Five Nights at Freddy's", 0, 48)); // NOI18N
        jLabel34.setText("JAVATICKET");

        javax.swing.GroupLayout jP_loginLayout = new javax.swing.GroupLayout(jP_login);
        jP_login.setLayout(jP_loginLayout);
        jP_loginLayout.setHorizontalGroup(
            jP_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_loginLayout.createSequentialGroup()
                .addGap(0, 184, Short.MAX_VALUE)
                .addGroup(jP_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jP_loginLayout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(jBtn_ingresar))
                    .addGroup(jP_loginLayout.createSequentialGroup()
                        .addGroup(jP_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jP_loginLayout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(jLabel3))
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jP_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jP_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTF_username)
                                .addComponent(jPF_password, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jLabel34, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(178, 178, 178))
        );
        jP_loginLayout.setVerticalGroup(
            jP_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_loginLayout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addComponent(jLabel34)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jP_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTF_username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jP_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jPF_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jBtn_ingresar)
                .addContainerGap(147, Short.MAX_VALUE))
        );

        getContentPane().add(jP_login, "card2");

        jLabel18.setText("USUARIOS");

        jLabel17.setText("EVENTOS");

        jLabel19.setText("SALIR");

        jLabel20.setText("REPORTES");

        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/3.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/2.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/1.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/4.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        Usuario.setText("Usuario: ");

        TipoUsuario.setText("Tipo de Usuario: ");

        javax.swing.GroupLayout jP_MenuPrincipalLayout = new javax.swing.GroupLayout(jP_MenuPrincipal);
        jP_MenuPrincipal.setLayout(jP_MenuPrincipalLayout);
        jP_MenuPrincipalLayout.setHorizontalGroup(
            jP_MenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_MenuPrincipalLayout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addGroup(jP_MenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jP_MenuPrincipalLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel17)))
                .addGap(10, 10, 10)
                .addGroup(jP_MenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jP_MenuPrincipalLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10)
                .addGroup(jP_MenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jP_MenuPrincipalLayout.createSequentialGroup()
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jP_MenuPrincipalLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(jLabel19)))
                .addContainerGap(108, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jP_MenuPrincipalLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jP_MenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TipoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jP_MenuPrincipalLayout.setVerticalGroup(
            jP_MenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jP_MenuPrincipalLayout.createSequentialGroup()
                .addContainerGap(197, Short.MAX_VALUE)
                .addGroup(jP_MenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jP_MenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jP_MenuPrincipalLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jP_MenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jP_MenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel18))))
                    .addGroup(jP_MenuPrincipalLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(97, 97, 97)
                .addComponent(Usuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TipoUsuario)
                .addGap(33, 33, 33))
        );

        getContentPane().add(jP_MenuPrincipal, "card3");

        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/4_1.png"))); // NOI18N
        jButton11.setText("Crear");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/5.png"))); // NOI18N
        jButton12.setText("Editar");
        jButton12.setToolTipText("");

        jButton13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/6.png"))); // NOI18N
        jButton13.setText("Eliminar");

        jButton15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/7.png"))); // NOI18N
        jButton15.setText("Ver");
        jButton15.setToolTipText("");

        jLabel21.setText("EVENTOS");

        jButton31.setText("Regresar");
        jButton31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton31ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jP_EventosLayout = new javax.swing.GroupLayout(jP_Eventos);
        jP_Eventos.setLayout(jP_EventosLayout);
        jP_EventosLayout.setHorizontalGroup(
            jP_EventosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_EventosLayout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addGroup(jP_EventosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jP_EventosLayout.createSequentialGroup()
                        .addGroup(jP_EventosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton13))
                        .addGap(18, 18, 18)
                        .addGroup(jP_EventosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jP_EventosLayout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(jLabel21)))
                .addContainerGap(140, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jP_EventosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton31)
                .addGap(24, 24, 24))
        );
        jP_EventosLayout.setVerticalGroup(
            jP_EventosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_EventosLayout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addComponent(jLabel21)
                .addGap(28, 28, 28)
                .addGroup(jP_EventosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton11)
                    .addComponent(jButton12))
                .addGap(18, 18, 18)
                .addGroup(jP_EventosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton13)
                    .addComponent(jButton15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 137, Short.MAX_VALUE)
                .addComponent(jButton31)
                .addGap(22, 22, 22))
        );

        getContentPane().add(jP_Eventos, "card4");

        jLabel22.setText("TIPO DE EVENTO");

        jButton16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/1_1.png"))); // NOI18N
        jButton16.setText("DEPORTIVO");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });

        jButton17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/2_1.png"))); // NOI18N
        jButton17.setText("MUSICAL");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });

        jButton18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/3_1.png"))); // NOI18N
        jButton18.setText("RELIGIOSO");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });

        jButton33.setText("Regresar");
        jButton33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton33ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jP_TEventoLayout = new javax.swing.GroupLayout(jP_TEvento);
        jP_TEvento.setLayout(jP_TEventoLayout);
        jP_TEventoLayout.setHorizontalGroup(
            jP_TEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_TEventoLayout.createSequentialGroup()
                .addContainerGap(124, Short.MAX_VALUE)
                .addGroup(jP_TEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jP_TEventoLayout.createSequentialGroup()
                        .addGroup(jP_TEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jP_TEventoLayout.createSequentialGroup()
                                .addComponent(jButton16)
                                .addGap(18, 18, 18)
                                .addComponent(jButton17, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jP_TEventoLayout.createSequentialGroup()
                                .addGap(86, 86, 86)
                                .addComponent(jButton18))
                            .addGroup(jP_TEventoLayout.createSequentialGroup()
                                .addGap(114, 114, 114)
                                .addComponent(jLabel22)))
                        .addGap(100, 100, 100))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jP_TEventoLayout.createSequentialGroup()
                        .addComponent(jButton33)
                        .addGap(22, 22, 22))))
        );
        jP_TEventoLayout.setVerticalGroup(
            jP_TEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_TEventoLayout.createSequentialGroup()
                .addGap(146, 146, 146)
                .addComponent(jLabel22)
                .addGap(18, 18, 18)
                .addGroup(jP_TEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton16)
                    .addComponent(jButton17))
                .addGap(18, 18, 18)
                .addComponent(jButton18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                .addComponent(jButton33)
                .addGap(31, 31, 31))
        );

        getContentPane().add(jP_TEvento, "card5");

        jP_CrearEventoD.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("CREAR EVENTO DEPORTIVO");
        jP_CrearEventoD.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, -1, -1));

        jLabel5.setText("Titulo del evento");
        jP_CrearEventoD.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, -1, -1));
        jP_CrearEventoD.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, 159, -1));

        jLabel6.setText("Descripción");
        jP_CrearEventoD.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, -1, -1));
        jP_CrearEventoD.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, 159, -1));

        jLabel7.setText("Fecha del Evento");
        jP_CrearEventoD.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, -1, -1));
        jP_CrearEventoD.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, 159, -1));

        jLabel8.setText("Monto");
        jP_CrearEventoD.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 37, -1));
        jP_CrearEventoD.add(jSpinner1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 200, 113, -1));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Futbol", "Tenis", "Baseball" }));
        jP_CrearEventoD.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 290, 160, -1));

        jLabel10.setText("Tipo de Evento");
        jP_CrearEventoD.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, -1, -1));

        jLabel11.setText("Equipo 1");
        jP_CrearEventoD.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 330, -1, -1));
        jP_CrearEventoD.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 330, 159, -1));

        jLabel12.setText("Equipo 2");
        jP_CrearEventoD.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 370, -1, -1));
        jP_CrearEventoD.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 360, 159, -1));

        jLabel13.setText("Personas");
        jP_CrearEventoD.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, -1, -1));
        jP_CrearEventoD.add(jSpinner2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 240, 113, -1));

        jButton5.setText("Crear");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jP_CrearEventoD.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 410, -1, -1));
        jP_CrearEventoD.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 330, 159, -1));

        jButton19.setText("Regresar");
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });
        jP_CrearEventoD.add(jButton19, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 450, -1, -1));

        jLabel35.setText("Codigo");
        jP_CrearEventoD.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, -1, -1));
        jP_CrearEventoD.add(jTextField13, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 50, 159, -1));

        getContentPane().add(jP_CrearEventoD, "card6");

        jP_CrearEventoM.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setText("CREAR EVENTO MUSICAL");
        jP_CrearEventoM.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, -1, -1));

        jLabel14.setText("Titulo del evento");
        jP_CrearEventoM.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, -1, -1));
        jP_CrearEventoM.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, 159, -1));

        jLabel23.setText("Descripción");
        jP_CrearEventoM.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, -1, -1));
        jP_CrearEventoM.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, 159, -1));

        jLabel24.setText("Fecha del Evento");
        jP_CrearEventoM.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, -1, -1));
        jP_CrearEventoM.add(jDateChooser2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, 159, -1));

        jLabel25.setText("Monto");
        jP_CrearEventoM.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 37, -1));
        jP_CrearEventoM.add(jSpinner3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 200, 113, -1));

        jLabel26.setText("Tipo de Evento");
        jP_CrearEventoM.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, -1, -1));

        jLabel29.setText("Personas");
        jP_CrearEventoM.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, -1, -1));
        jP_CrearEventoM.add(jSpinner4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 240, 113, -1));

        jButton6.setText("Crear");
        jP_CrearEventoM.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 360, -1, -1));

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "POP", "ROCK", "RAP", "CLASICA", "REGGEATON", "OTRO" }));
        jP_CrearEventoM.add(jComboBox5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 290, 160, -1));

        jButton20.setText("Regresar");
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });
        jP_CrearEventoM.add(jButton20, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 420, -1, -1));

        getContentPane().add(jP_CrearEventoM, "card7");

        jP_CrearEventoR.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel28.setText("CREAR EVENTO RELIGIOSO");
        jP_CrearEventoR.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, -1, -1));

        jLabel30.setText("Titulo del evento");
        jP_CrearEventoR.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, -1, -1));
        jP_CrearEventoR.add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, 159, -1));

        jLabel31.setText("Descripción");
        jP_CrearEventoR.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, -1, -1));
        jP_CrearEventoR.add(jTextField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, 159, -1));

        jLabel32.setText("Fecha del Evento");
        jP_CrearEventoR.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, -1, -1));
        jP_CrearEventoR.add(jDateChooser3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, 159, -1));

        jLabel33.setText("Monto");
        jP_CrearEventoR.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 37, -1));
        jP_CrearEventoR.add(jSpinner5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 200, 113, -1));

        jLabel36.setText("Personas");
        jP_CrearEventoR.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, -1, -1));
        jP_CrearEventoR.add(jSpinner6, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 240, 113, -1));

        jButton7.setText("Crear");
        jP_CrearEventoR.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 310, -1, -1));

        jButton21.setText("Regresar");
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });
        jP_CrearEventoR.add(jButton21, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 380, -1, -1));

        getContentPane().add(jP_CrearEventoR, "card7");

        jLabel15.setText("ID");
        jLabel15.setToolTipText("");

        jButton14.setText("Eliminar");

        jLabel16.setText("Eliminar Evento");

        javax.swing.GroupLayout jP_EliminarEventoLayout = new javax.swing.GroupLayout(jP_EliminarEvento);
        jP_EliminarEvento.setLayout(jP_EliminarEventoLayout);
        jP_EliminarEventoLayout.setHorizontalGroup(
            jP_EliminarEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jP_EliminarEventoLayout.createSequentialGroup()
                .addContainerGap(173, Short.MAX_VALUE)
                .addComponent(jLabel15)
                .addGap(28, 28, 28)
                .addGroup(jP_EliminarEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jP_EliminarEventoLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel16))
                    .addGroup(jP_EliminarEventoLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jButton14)))
                .addGap(180, 180, 180))
        );
        jP_EliminarEventoLayout.setVerticalGroup(
            jP_EliminarEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_EliminarEventoLayout.createSequentialGroup()
                .addGap(171, 171, 171)
                .addComponent(jLabel16)
                .addGap(18, 18, 18)
                .addGroup(jP_EliminarEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addGap(18, 18, 18)
                .addComponent(jButton14)
                .addContainerGap(205, Short.MAX_VALUE))
        );

        getContentPane().add(jP_EliminarEvento, "card9");

        jButton22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/4_1.png"))); // NOI18N
        jButton22.setText("Crear");
        jButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton22ActionPerformed(evt);
            }
        });

        jButton23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/5.png"))); // NOI18N
        jButton23.setText("Editar");
        jButton23.setToolTipText("");

        jButton24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/6.png"))); // NOI18N
        jButton24.setText("Eliminar");

        jLabel43.setText("USUARIOS");

        jButton32.setText("Regresar");
        jButton32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton32ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jP_UsersLayout = new javax.swing.GroupLayout(jP_Users);
        jP_Users.setLayout(jP_UsersLayout);
        jP_UsersLayout.setHorizontalGroup(
            jP_UsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_UsersLayout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addGroup(jP_UsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jP_UsersLayout.createSequentialGroup()
                        .addComponent(jButton22, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton23, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jP_UsersLayout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(jLabel43)))
                .addContainerGap(140, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jP_UsersLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jP_UsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jP_UsersLayout.createSequentialGroup()
                        .addComponent(jButton24)
                        .addGap(209, 209, 209))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jP_UsersLayout.createSequentialGroup()
                        .addComponent(jButton32)
                        .addGap(30, 30, 30))))
        );
        jP_UsersLayout.setVerticalGroup(
            jP_UsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_UsersLayout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addComponent(jLabel43)
                .addGap(28, 28, 28)
                .addGroup(jP_UsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton22)
                    .addComponent(jButton23))
                .addGap(18, 18, 18)
                .addComponent(jButton24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 118, Short.MAX_VALUE)
                .addComponent(jButton32)
                .addGap(41, 41, 41))
        );

        getContentPane().add(jP_Users, "card4");

        jLabel37.setText("CREAR USUARIO");

        jLabel38.setText("Tipo");

        jLabel39.setText("Nombre");

        jLabel40.setText("Username");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ADMINISTRADOR", "CONTENIDOS", "LIMITADO" }));

        jLabel41.setText("Contraseña");

        jLabel42.setText("Edad");

        jButton8.setText("Crear");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jP_CrearUserLayout = new javax.swing.GroupLayout(jP_CrearUser);
        jP_CrearUser.setLayout(jP_CrearUserLayout);
        jP_CrearUserLayout.setHorizontalGroup(
            jP_CrearUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jP_CrearUserLayout.createSequentialGroup()
                .addGap(0, 140, Short.MAX_VALUE)
                .addGroup(jP_CrearUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel38, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel39, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel40, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel41, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel42, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(jP_CrearUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel37)
                    .addComponent(jTF_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTF_usernamee1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTF_contra, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jP_CrearUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jButton8)
                        .addComponent(jS_edad, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(113, 113, 113))
        );
        jP_CrearUserLayout.setVerticalGroup(
            jP_CrearUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_CrearUserLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel37)
                .addGap(30, 30, 30)
                .addGroup(jP_CrearUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel38)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jP_CrearUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel39)
                    .addComponent(jTF_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jP_CrearUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel40)
                    .addComponent(jTF_usernamee1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jP_CrearUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel41)
                    .addComponent(jTF_contra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jP_CrearUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel42)
                    .addComponent(jS_edad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(jButton8)
                .addContainerGap(126, Short.MAX_VALUE))
        );

        getContentPane().add(jP_CrearUser, "card10");

        jButton25.setText("Eventos realizados");
        jButton25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton25ActionPerformed(evt);
            }
        });

        jButton26.setText("Eventos futuros");
        jButton26.setToolTipText("");

        jButton27.setText("Ingreso generado por fecha");
        jButton27.setToolTipText("");

        jButton28.setText("Eventos cancelados");

        jButton29.setText("Ver Perfil del Usuario");

        jButton30.setText("Regresar a Menú Principal");
        jButton30.setToolTipText("");
        jButton30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton30ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jP_ReportesLayout = new javax.swing.GroupLayout(jP_Reportes);
        jP_Reportes.setLayout(jP_ReportesLayout);
        jP_ReportesLayout.setHorizontalGroup(
            jP_ReportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_ReportesLayout.createSequentialGroup()
                .addGap(195, 195, 195)
                .addGroup(jP_ReportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton25, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton26, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton27)
                    .addComponent(jButton28, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton29, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton30, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(184, Short.MAX_VALUE))
        );
        jP_ReportesLayout.setVerticalGroup(
            jP_ReportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jP_ReportesLayout.createSequentialGroup()
                .addContainerGap(76, Short.MAX_VALUE)
                .addComponent(jButton25, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton26, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton28, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton27, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton29, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton30, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
        );

        getContentPane().add(jP_Reportes, "card12");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        jP_MenuPrincipal.setVisible(false);
        jP_Users.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        jP_MenuPrincipal.setVisible(false);
        jP_Eventos.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        jP_MenuPrincipal.setVisible(false);
        jP_Reportes.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        int respuesta = JOptionPane.showConfirmDialog
            (rootPane, "¿Está seguro que quiere salir?", 
                "SALIR", JOptionPane.OK_CANCEL_OPTION);
        
        if (respuesta == JOptionPane.OK_OPTION) {
            jP_MenuPrincipal.setVisible(false);
            jP_login.setVisible(true);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jBtn_ingresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_ingresarActionPerformed
        // TODO add your handling code here:
        try {
            if (jTF_username.getText().isEmpty() || jPF_password.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Llene las casillas.");
            } else {
                AdminUser au = new AdminUser("./datos.txt");
                au.cargarArchivo();

                boolean usuarioValido = false;

                for (user usuario : au.getListaUser()) {
                    if (usuario.getUsername().equals(jTF_username.getText()) && usuario.getPassword().equals(jPF_password.getText())) {
                        usuarioValido = true;
                        JOptionPane.showMessageDialog(this, "Bienvenido!!");
                        jP_login.setVisible(false);
                        jP_MenuPrincipal.setVisible(true);
                        usuarioEnSesion=jTF_username.getText();
                        TipoUsuarioEnSesion = usuario.getTipoUsuario().toString();
                    }
                }

                if (!usuarioValido && jTF_username.getText().equalsIgnoreCase("admin") && jPF_password.getText().equals("supersecreto")) {
                    usuarioValido = true;
                    JOptionPane.showMessageDialog(this, "BIENVENIDO");
                    jP_login.setVisible(false);
                    jP_MenuPrincipal.setVisible(true);
                    usuarioEnSesion=jTF_username.getText();
                    TipoUsuarioEnSesion = "ADMINISTRADOR";
                }

                if (!usuarioValido) {
                    JOptionPane.showMessageDialog(this, "Usuario o contraseña incorrectos.");
                }
                Usuario.setText("Usuario: "+usuarioEnSesion);
                TipoUsuario.setText("Tipo de Usuario: "+TipoUsuarioEnSesion);
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error al intentar ingresar: " + e.getMessage());
        }
    }//GEN-LAST:event_jBtn_ingresarActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        jP_Eventos.setVisible(false);
        jP_TEvento.setVisible(true);
        
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        // TODO add your handling code here:
        jP_TEvento.setVisible(false);
        jP_CrearEventoD.setVisible(true);
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        // TODO add your handling code here:
        jP_CrearEventoD.setVisible(false);
        jP_TEvento.setVisible(true);
    }//GEN-LAST:event_jButton19ActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
        // TODO add your handling code here:
        jP_CrearEventoM.setVisible(false);
        jP_TEvento.setVisible(true);
    }//GEN-LAST:event_jButton20ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        // TODO add your handling code here:
        jP_TEvento.setVisible(false);
        jP_CrearEventoM.setVisible(true);
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
        // TODO add your handling code here:
        jP_CrearEventoR.setVisible(false);
        jP_TEvento.setVisible(true);
    }//GEN-LAST:event_jButton21ActionPerformed

    private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton22ActionPerformed
        // TODO add your handling code here:
        jP_Users.setVisible(false);
        jP_CrearUser.setVisible(true);
    }//GEN-LAST:event_jButton22ActionPerformed

    private void jButton25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton25ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton25ActionPerformed

    private void jButton30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton30ActionPerformed
        // TODO add your handling code here:
        jP_Reportes.setVisible(false);
        jP_MenuPrincipal.setVisible(true);
    }//GEN-LAST:event_jButton30ActionPerformed

    private void jButton31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton31ActionPerformed
        // TODO add your handling code here:
        jP_Eventos.setVisible(false);
        jP_MenuPrincipal.setVisible(true);
    }//GEN-LAST:event_jButton31ActionPerformed

    private void jButton32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton32ActionPerformed
        // TODO add your handling code here:
        jP_Users.setVisible(false);
        jP_MenuPrincipal.setVisible(true);
    }//GEN-LAST:event_jButton32ActionPerformed

    private void jButton33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton33ActionPerformed
        // TODO add your handling code here:
        jP_TEvento.setVisible(false);
        jP_Eventos.setVisible(true);
    }//GEN-LAST:event_jButton33ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        // TODO add your handling code here:
        jP_TEvento.setVisible(false);
        jP_CrearEventoR.setVisible(true);
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        try {
            if (camposValidos()) {
                int edad= (int)jS_edad.getComponentCount();
                user p = new user(jTF_nombre.getText(), jTF_usernamee1.getText(), jTF_contra.getText(), edad) {
                    String tipoUsuario = (String) jComboBox1.getSelectedItem();

                    @Override
                    public TipoUser getTipoUsuario() {
                        switch (tipoUsuario) {
                            case "ADMINISTRADOR":
                                return TipoUser.ADMINISTRADOR;
                            case "LIMITADO":
                                return TipoUser.LIMITADO;
                            case "CONTENIDO":
                                return TipoUser.CONTENIDOS;
                            default:
                                return TipoUser.ADMINISTRADOR;
                        }
                    }
                };
                AdminUser adminUser = new AdminUser("./datos.txt");
                adminUser.cargarArchivo();
                adminUser.setUser(p);
                adminUser.escribirArchivo();
                
                JOptionPane.showMessageDialog(this, "Usuario creado exitosamente");
            } else {
                JOptionPane.showMessageDialog(this, "Complete todos los campos antes de crear un usuario");
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error al crear el usuario");
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }
    
    public void Inicio(){
        jP_login.setVisible(true);
        jP_MenuPrincipal.setVisible(false);
        jP_CrearEventoD.setVisible(false);
        jP_CrearEventoM.setVisible(false);
        jP_EliminarEvento.setVisible(false);
        jP_Eventos.setVisible(false);
        jP_Users.setVisible(false);
        jP_TEvento.setVisible(false);
        SpinnerNumberModel spinnerModel = new SpinnerNumberModel(1, 1, 25000, 1);
        jSpinner3.setModel(spinnerModel); 
        Date fechaActual = new Date();
        SimpleDateFormat formatoFecha = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss");
        String fechaFormateada = formatoFecha.format(fechaActual);
        jDateChooser1.setMinSelectableDate(fechaActual);
        jDateChooser2.setMinSelectableDate(fechaActual);
        jDateChooser3.setMinSelectableDate(fechaActual);
    }
    
    private boolean camposValidos() {
        return !jTF_nombre.getText().isEmpty() && !jTF_usernamee1.getText().isEmpty() && !jTF_contra.getText().isEmpty();
    }
    
    String usuarioEnSesion;
    String TipoUsuarioEnSesion;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel TipoUsuario;
    private javax.swing.JLabel Usuario;
    private javax.swing.JButton jBtn_ingresar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton31;
    private javax.swing.JButton jButton32;
    private javax.swing.JButton jButton33;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox5;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private com.toedter.calendar.JDateChooser jDateChooser3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField jPF_password;
    private javax.swing.JPanel jP_CrearEventoD;
    private javax.swing.JPanel jP_CrearEventoM;
    private javax.swing.JPanel jP_CrearEventoR;
    private javax.swing.JPanel jP_CrearUser;
    private javax.swing.JPanel jP_EliminarEvento;
    private javax.swing.JPanel jP_Eventos;
    private javax.swing.JPanel jP_MenuPrincipal;
    private javax.swing.JPanel jP_Reportes;
    private javax.swing.JPanel jP_TEvento;
    private javax.swing.JPanel jP_Users;
    private javax.swing.JPanel jP_login;
    private javax.swing.JSpinner jS_edad;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner jSpinner2;
    private javax.swing.JSpinner jSpinner3;
    private javax.swing.JSpinner jSpinner4;
    private javax.swing.JSpinner jSpinner5;
    private javax.swing.JSpinner jSpinner6;
    private javax.swing.JTextField jTF_contra;
    private javax.swing.JTextField jTF_nombre;
    private javax.swing.JTextField jTF_username;
    private javax.swing.JTextField jTF_usernamee1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    // End of variables declaration//GEN-END:variables
}
